# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import users_pb2 as users__pb2


class UsersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/users.Users/CreateUser',
        request_serializer=users__pb2.UserReq.SerializeToString,
        response_deserializer=users__pb2.StatusRes.FromString,
        )
    self.MakePremium = channel.unary_unary(
        '/users.Users/MakePremium',
        request_serializer=users__pb2.PhoneNumReq.SerializeToString,
        response_deserializer=users__pb2.MPResponse.FromString,
        )
    self.DeleteUser = channel.unary_unary(
        '/users.Users/DeleteUser',
        request_serializer=users__pb2.PhoneNumReq.SerializeToString,
        response_deserializer=users__pb2.StatusRes.FromString,
        )
    self.checkPremium = channel.unary_unary(
        '/users.Users/checkPremium',
        request_serializer=users__pb2.PhoneNumReq.SerializeToString,
        response_deserializer=users__pb2.CheckRes.FromString,
        )


class UsersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MakePremium(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def checkPremium(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=users__pb2.UserReq.FromString,
          response_serializer=users__pb2.StatusRes.SerializeToString,
      ),
      'MakePremium': grpc.unary_unary_rpc_method_handler(
          servicer.MakePremium,
          request_deserializer=users__pb2.PhoneNumReq.FromString,
          response_serializer=users__pb2.MPResponse.SerializeToString,
      ),
      'DeleteUser': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteUser,
          request_deserializer=users__pb2.PhoneNumReq.FromString,
          response_serializer=users__pb2.StatusRes.SerializeToString,
      ),
      'checkPremium': grpc.unary_unary_rpc_method_handler(
          servicer.checkPremium,
          request_deserializer=users__pb2.PhoneNumReq.FromString,
          response_serializer=users__pb2.CheckRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'users.Users', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
