# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wallet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wallet.proto',
  package='wallet',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cwallet.proto\x12\x06wallet\"B\n\x08TopupReq\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x10\n\x08\x66romBank\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"\x1b\n\tStatusRes\x12\x0e\n\x06status\x18\x01 \x01(\t28\n\x06Wallet\x12.\n\x05TopUp\x12\x10.wallet.TopupReq\x1a\x11.wallet.StatusRes\"\x00\x62\x06proto3')
)




_TOPUPREQ = _descriptor.Descriptor(
  name='TopupReq',
  full_name='wallet.TopupReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='wallet.TopupReq.phone_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromBank', full_name='wallet.TopupReq.fromBank', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='wallet.TopupReq.amount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=90,
)


_STATUSRES = _descriptor.Descriptor(
  name='StatusRes',
  full_name='wallet.StatusRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='wallet.StatusRes.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['TopupReq'] = _TOPUPREQ
DESCRIPTOR.message_types_by_name['StatusRes'] = _STATUSRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopupReq = _reflection.GeneratedProtocolMessageType('TopupReq', (_message.Message,), {
  'DESCRIPTOR' : _TOPUPREQ,
  '__module__' : 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:wallet.TopupReq)
  })
_sym_db.RegisterMessage(TopupReq)

StatusRes = _reflection.GeneratedProtocolMessageType('StatusRes', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRES,
  '__module__' : 'wallet_pb2'
  # @@protoc_insertion_point(class_scope:wallet.StatusRes)
  })
_sym_db.RegisterMessage(StatusRes)



_WALLET = _descriptor.ServiceDescriptor(
  name='Wallet',
  full_name='wallet.Wallet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=121,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='TopUp',
    full_name='wallet.Wallet.TopUp',
    index=0,
    containing_service=None,
    input_type=_TOPUPREQ,
    output_type=_STATUSRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WALLET)

DESCRIPTOR.services_by_name['Wallet'] = _WALLET

# @@protoc_insertion_point(module_scope)
