# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import wallet_pb2 as wallet__pb2


class WalletStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TopUp = channel.unary_unary(
        '/wallet.Wallet/TopUp',
        request_serializer=wallet__pb2.TopupReq.SerializeToString,
        response_deserializer=wallet__pb2.StatusRes.FromString,
        )


class WalletServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TopUp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WalletServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TopUp': grpc.unary_unary_rpc_method_handler(
          servicer.TopUp,
          request_deserializer=wallet__pb2.TopupReq.FromString,
          response_serializer=wallet__pb2.StatusRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'wallet.Wallet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
